//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver
    {
        public string Deliver_ID { get; set; }
        public string PO_NO { get; set; }
        public string Truck_NO { get; set; }
        public string Driver_ID { get; set; }
        public Nullable<System.DateTime> Arr_Date { get; set; }
        public Nullable<System.TimeSpan> Arr_Time { get; set; }
        public string Location_ID { get; set; }
    
        public virtual Depart_Location Depart_Location { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Purchase_Order Purchase_Order { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
