//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public string Expense1 { get; set; }
        public Nullable<double> Price_Per_day { get; set; }
    }
}
