//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public System.DateTime date { get; set; }
        public Nullable<double> Begin_D_L_ { get; set; }
        public Nullable<double> Begin_G_L_ { get; set; }
        public Nullable<double> Begin_D_B_ { get; set; }
        public Nullable<double> Begin_G_B_ { get; set; }
        public Nullable<double> AmountSold_D_L_ { get; set; }
        public Nullable<double> AmountSold_G_L_ { get; set; }
        public Nullable<double> AmountSold_D_B_ { get; set; }
        public Nullable<double> AmountSold_G_B_ { get; set; }
        public Nullable<double> AmountPurchase_D_L_ { get; set; }
        public Nullable<double> AmountPurchase_G_L_ { get; set; }
        public Nullable<double> AmountPurchase_D_B_ { get; set; }
        public Nullable<double> AmountPurchase_G_B_ { get; set; }
        public Nullable<double> Balance_D_L_ { get; set; }
        public Nullable<double> Balance_G_L_ { get; set; }
        public Nullable<double> Balance_D_B_ { get; set; }
        public Nullable<double> Balance_G_B_ { get; set; }
    }
}
