//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapstoneV3Entities9 : DbContext
    {
        public CapstoneV3Entities9()
            : base("name=CapstoneV3Entities9")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Deliver> Deliver { get; set; }
        public virtual DbSet<Depart_Location> Depart_Location { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<Income> Income { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Purchase_Order> Purchase_Order { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Transac> Transac { get; set; }
        public virtual DbSet<Transca> Transca { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
    }
}
