//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Purchase_Order = new HashSet<Purchase_Order>();
        }
    
        public string e_Bill_NO { get; set; }
        public string Customer_ID { get; set; }
        public string Invoice_NO { get; set; }
        public string Payment_Method { get; set; }
        public string Transfer_AC_Name { get; set; }
        public string Transfer_AC_NO { get; set; }
        public string Recieve_AC_Name { get; set; }
        public string Recieve_AC_NO { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order> Purchase_Order { get; set; }
    }
}
