//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public System.DateTime Date { get; set; }
        public Nullable<double> Gasohol95_Cost { get; set; }
        public Nullable<double> Gasohol95_Price { get; set; }
        public Nullable<double> Diesel_Cost { get; set; }
        public Nullable<double> Diesel_Price { get; set; }
    }
}
