//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_Order()
        {
            this.Deliver = new HashSet<Deliver>();
        }
    
        public string PO_NO { get; set; }
        public string e_Bill_NO { get; set; }
        public string Location_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Staff_ID { get; set; }
        public string Gas_type { get; set; }
        public Nullable<System.TimeSpan> Filling_time { get; set; }
        public Nullable<double> Fuel_Amount { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<System.DateTime> Deliver_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deliver> Deliver { get; set; }
        public virtual Depart_Location Depart_Location { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
