//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backendtest.DbContxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transca
    {
        public double No { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Action { get; set; }
        public string Type { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
